export enum NETWORKS_CHAINS {
  MATIC_CHAIN_ID = 137,
  MATIC_TEST_CHAIN_ID = 80001,
  ETHER_CHAIN_ID = 1,
  ETHER_TEST_CHAIN_ID = 4,
  BSC_CHAIN_ID = 56,
  BSC_TEST_CHAIN_ID = 97
}

export enum NETWORKS_CHAINS_HEX {
  MATIC_CHAIN_ID = '0x89',
  MATIC_TEST_CHAIN_ID = '0x13881',
  ETHER_CHAIN_ID = '0x89',
  ETHER_TEST_CHAIN_ID = '0x4',
  BSC_CHAIN_ID = '0x38',
  BSC_TEST_CHAIN_ID = '0x61'
}
