import { BLOCKCHAIN_WORKSPACES } from '@shared/enums';

export type BlockChainNetwork = BLOCKCHAIN_WORKSPACES.ETHEREUM
  | BLOCKCHAIN_WORKSPACES.MATIC
  | BLOCKCHAIN_WORKSPACES.BINANCE
  | BLOCKCHAIN_WORKSPACES.OTHER;
